"""added cell model

Revision ID: 42c6ae6c390e
Revises: 9cc9eed43339
Create Date: 2019-03-16 10:37:28.860382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42c6ae6c390e'
down_revision = '9cc9eed43339'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_type', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('register_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['main_approval_statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['main_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_cells')
    # ### end Alembic commands ###

