"""added affil id for the relationship

Revision ID: 5ed8aa147090
Revises: 8bbb8beb8717
Create Date: 2019-03-12 12:52:39.870074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed8aa147090'
down_revision = '8bbb8beb8717'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_user_profiles', sa.Column('affil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'main_user_profiles', 'main_institutions', ['affil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_user_profiles', type_='foreignkey')
    op.drop_column('main_user_profiles', 'affil_id')
    # ### end Alembic commands ###

