"""added view count to some models

Revision ID: 6cdf42f05327
Revises: 3b87e445d430
Create Date: 2019-03-16 17:36:25.420048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdf42f05327'
down_revision = '3b87e445d430'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_cells', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('main_events', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('main_projects', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_projects', 'view_count')
    op.drop_column('main_events', 'view_count')
    op.drop_column('main_cells', 'view_count')
    # ### end Alembic commands ###

