"""added ApprovalStatus model

Revision ID: 806de03f238d
Revises: 5ed8aa147090
Create Date: 2019-03-12 13:02:16.564515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806de03f238d'
down_revision = '5ed8aa147090'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_approval_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('main_institutions', sa.Column('adder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'main_institutions', 'main_users', ['adder_id'], ['id'])
    op.add_column('main_projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('main_projects', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'main_projects', 'main_users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'main_projects', 'main_approval_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_projects', type_='foreignkey')
    op.drop_constraint(None, 'main_projects', type_='foreignkey')
    op.drop_column('main_projects', 'status_id')
    op.drop_column('main_projects', 'creator_id')
    op.drop_constraint(None, 'main_institutions', type_='foreignkey')
    op.drop_column('main_institutions', 'adder_id')
    op.drop_table('main_approval_statuses')
    # ### end Alembic commands ###

