"""added title and academic title field

Revision ID: 8bbb8beb8717
Revises: 2e625e29700d
Create Date: 2019-03-12 12:49:06.182272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbb8beb8717'
down_revision = '2e625e29700d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_user_profiles', sa.Column('academic_title_th', sa.String(length=128), nullable=True))
    op.add_column('main_user_profiles', sa.Column('title_th', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_user_profiles', 'title_th')
    op.drop_column('main_user_profiles', 'academic_title_th')
    # ### end Alembic commands ###

