"""added cell ID to Project model

Revision ID: 8d3d3961a044
Revises: 7d1ddc28ac85
Create Date: 2019-03-18 07:20:28.040981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3d3961a044'
down_revision = '7d1ddc28ac85'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_projects', sa.Column('cell_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'main_projects', 'main_cells', ['cell_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_projects', type_='foreignkey')
    op.drop_column('main_projects', 'cell_id')
    # ### end Alembic commands ###

