"""added last view field to the project model

Revision ID: cc5454887f58
Revises: 8d3d3961a044
Create Date: 2019-03-18 07:21:48.159740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5454887f58'
down_revision = '8d3d3961a044'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_projects', sa.Column('last_view', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_projects', 'last_view')
    # ### end Alembic commands ###

