version: "3.4"
services:
  web:
    build: .
    depends_on:
      - pg
    ports:
      - 5000:5000
      - 80:5000
    env_file:
      - web_variables.env
    environment:
      - FLASK_DEBUG
      - POSTGRES_PASSWORD
    volumes:
      - ./app:/app
  pg:
    image: postgres:11
    env_file:
      - pg_variables.env
    volumes:
      - screg-vol:/var/lib/postgresql/data

volumes:
  screg-vol:
    external: true
